<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        header {
            text-align: center;
            padding: 10px;
            background-color: #f2f2f2;
        }

        h1 {
            color: #333;
        }

        .contact-info {
            margin-top: 20px;
        }

        .contact-info p {
            margin: 10px 0;
        }
    </style>
</head>
<body>

    <header>
        <h1>Contact Us</h1>
    </header>

    <div class="contact-info">
        <p><strong>Phone Number:</strong> 9632228366</p>
        <p><strong>Email:</strong> <a href="mailto:carbonvyn13@gmail.com">carbonvyn13@gmail.com</a></p>
        <p><strong>Address:</strong> Affinity Blossom, 6th B Cross Road, Carmelaram, Hadosiddapura, Chikkakannalli, Bengaluru, Karnataka 560035</p>
    </div>

</body>
</html>
